#!/usr/bin/env node
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import http from 'node:http';
import net from 'node:net';
import Database from 'better-sqlite3';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const GATEWAY = join(ROOT, 'lib', 'gateway.mjs');
const KEY = 'backend-hardening-test-key';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const freePort = () => new Promise((resolve, reject) => { const s=net.createServer(); s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});s.on('error',reject); });
function request(port, { path='/', method='GET', body=null, headers={} }={}) {
  return new Promise((resolve,reject)=>{ const req=http.request({host:'127.0.0.1',port,path,method,headers:{Host:`127.0.0.1:${port}`,...headers}},res=>{const cs=[];res.on('data',c=>cs.push(c));res.on('end',()=>{const raw=Buffer.concat(cs).toString();let json;try{json=JSON.parse(raw)}catch{}resolve({status:res.statusCode,raw,json,headers:res.headers});});});req.on('error',reject);if(body!=null)req.write(body);req.end(); });
}
async function wait(port, child){for(let i=0;i<80;i++){if(child.exitCode!=null)throw new Error('gateway exited');try{if((await request(port,{path:'/health'})).status===200)return;}catch{}await sleep(75);}throw new Error('health timeout');}
let pass=0,fail=0; async function test(name,fn){try{await fn();pass++;console.log(`  ✓ ${name}`)}catch(e){fail++;console.error(`  ✗ ${name}: ${e.message}`)}}

const data=mkdtempSync(join(tmpdir(),'kigw-backend-'));
writeFileSync(join(data,'.gateway_key'),KEY+'\n',{mode:0o600});
// Legacy schema with no user_version and missing v2 columns.
const legacy=new Database(join(data,'ki-gateway.db'));
legacy.exec(`CREATE TABLE request_log(id TEXT PRIMARY KEY,ts TEXT NOT NULL,ts_ms INTEGER NOT NULL,provider TEXT,model TEXT,status INTEGER,ok INTEGER,latency_ms INTEGER,tokens INTEGER,error TEXT); CREATE TABLE audit_log(id TEXT PRIMARY KEY,ts TEXT NOT NULL,ts_ms INTEGER NOT NULL,action TEXT NOT NULL,target TEXT,detail TEXT,actor TEXT);`); legacy.close();
const port=await freePort();
const child=spawn(process.execPath,[GATEWAY],{cwd:ROOT,env:{...process.env,KIGW_PORT:String(port),KIGW_HOST:'127.0.0.1',KIGW_DATA_DIR:data,KIGW_GATEWAY_KEY:KEY,G2A_BASE:'http://127.0.0.1:9',KIGW_ADMIN_BODY_LIMIT:'8192',KIGW_CHAT_BODY_LIMIT:'16384'},stdio:['ignore','pipe','pipe']});
let stderr='';child.stderr.on('data',d=>stderr+=d);
try{
 await wait(port,child); const auth={Authorization:`Bearer ${KEY}`}; const jsonAuth={...auth,'Content-Type':'application/json'};
 await test('migrates legacy SQLite schema and sets user_version',()=>{const db=new Database(join(data,'ki-gateway.db'));assert.equal(db.pragma('user_version',{simple:true}),2);const cols=new Set(db.prepare('pragma table_info(request_log)').all().map(x=>x.name));assert.ok(cols.has('prompt_tokens'));assert.ok(cols.has('key_id'));db.close();});
 await test('rejects wrong JSON content type',async()=>{const r=await request(port,{path:'/admin/providers/toggle',method:'POST',headers:{...auth,'Content-Type':'text/plain'},body:'{}'});assert.equal(r.status,415);assert.equal(r.json?.error?.code,'unsupported_media_type');});
 await test('rejects oversized admin body before JSON parsing',async()=>{const r=await request(port,{path:'/admin/providers/toggle',method:'POST',headers:jsonAuth,body:JSON.stringify({pad:'x'.repeat(9000)})});assert.equal(r.status,413);assert.equal(r.json?.error?.code,'body_too_large');});
 await test('blocks private provider URL by default',async()=>{const r=await request(port,{path:'/admin/providers',method:'POST',headers:jsonAuth,body:JSON.stringify({prefix:'evil',name:'evil',type:'openai',baseUrl:'http://127.0.0.1:9999/v1',key:'x',models:[{id:'m'}]})});assert.equal(r.status,400);assert.equal(r.json?.code,'network_policy');});
 await test('blocks IPv4-mapped IPv6 private URL variants',async()=>{for(const host of ['[::ffff:7f00:1]','[::ffff:0a00:1]','[::ffff:a9fe:a9fe]']){const r=await request(port,{path:'/admin/providers',method:'POST',headers:jsonAuth,body:JSON.stringify({prefix:'mapped',name:'mapped',type:'openai',baseUrl:`http://${host}:9999/v1`,key:'x',models:[{id:'m'}]})});assert.equal(r.status,400,host);assert.equal(r.json?.code,'network_policy',host);}});
 await test('does not trust forwarded host/proto unless explicitly enabled',async()=>{const r=await request(port,{path:'/admin/session',method:'POST',headers:{...jsonAuth,Origin:'http://evil.example','X-Forwarded-Host':'evil.example','X-Forwarded-Proto':'https'},body:'{}'});assert.equal(r.status,403);assert.ok(!String(r.headers['set-cookie']||'').includes('__Host-kigw_session='));});
 await test('caps concurrent admin sessions and evicts the oldest idle session',async()=>{let firstCookie='';for(let i=0;i<101;i++){const r=await request(port,{path:'/admin/session',method:'POST',headers:{...jsonAuth,Origin:`http://127.0.0.1:${port}`},body:'{}'});assert.equal(r.status,200);if(i===0)firstCookie=String(r.headers['set-cookie']||'').split(';')[0];}const evicted=await request(port,{path:'/admin/providers',headers:{Cookie:firstCookie}});assert.equal(evicted.status,401);});
 await test('rejects an empty destructive restore',async()=>{const before=readFileSync(join(data,'providers.json'),'utf8');const r=await request(port,{path:'/admin/restore',method:'POST',headers:jsonAuth,body:JSON.stringify({version:2,secrets:'redacted',providers:{providers:{},proxyPools:[]}})});assert.equal(r.status,400);assert.equal(readFileSync(join(data,'providers.json'),'utf8'),before);});
 await test('proxy list and association response never return plaintext credentials',async()=>{const secret='proxy-pass-should-not-leak';const provider=await request(port,{path:'/admin/providers',method:'POST',headers:jsonAuth,body:JSON.stringify({prefix:'proxyassoc',name:'proxyassoc',type:'openai',baseUrl:'https://example.com/v1',key:'x',models:[{id:'m'}]})});assert.equal(provider.status,200);const add=await request(port,{path:'/admin/proxy-pools',method:'POST',headers:jsonAuth,body:JSON.stringify({url:`http://user:${secret}@example.com:8080`})});assert.equal(add.status,200);const list=await request(port,{path:'/admin/proxy-pools',headers:auth});assert.equal(list.status,200);assert.ok(!list.raw.includes(secret));assert.ok(!list.raw.includes('urlFull'));const pool=list.json?.items?.find(x=>x.hasCredentials);assert.equal(pool?.hasCredentials,true);const linked=await request(port,{path:'/admin/providers/proxy',method:'POST',headers:jsonAuth,body:JSON.stringify({prefix:'proxyassoc',proxyPoolId:pool.id})});assert.equal(linked.status,200);assert.ok(!linked.raw.includes(secret));assert.equal(linked.json?.pool?.url,undefined);});
 await test('OpenAI-compatible upstream errors are sanitized before returning or storing',async()=>{const secret='sk-upstream-secret-should-not-leak';const upstreamPort=await freePort();const upstream=http.createServer((req,res)=>{res.writeHead(401,{'Content-Type':'text/plain'});res.end(`Authorization: Bearer ${secret} http://user:password@internal.example/`);});await new Promise((resolve,reject)=>{upstream.once('error',reject);upstream.listen(upstreamPort,'127.0.0.1',resolve)});const isolated=mkdtempSync(join(tmpdir(),'kigw-upstream-error-'));const isolatedPort=await freePort();const isolatedKey='isolated-upstream-error-key';writeFileSync(join(isolated,'.gateway_key'),isolatedKey+'\n',{mode:0o600});writeFileSync(join(isolated,'providers.json'),JSON.stringify({version:1,providers:{leaktest:{name:'leaktest',type:'openai',baseUrl:`http://127.0.0.1:${upstreamPort}/v1`,key:'x',models:[{id:'m'}]}},proxyPools:[]}));const isolatedChild=spawn(process.execPath,[GATEWAY],{cwd:ROOT,env:{...process.env,KIGW_PORT:String(isolatedPort),KIGW_HOST:'127.0.0.1',KIGW_DATA_DIR:isolated,KIGW_GATEWAY_KEY:isolatedKey,KIGW_ALLOW_PRIVATE_NETWORKS:'1'},stdio:['ignore','pipe','pipe']});try{await wait(isolatedPort,isolatedChild);const r=await request(isolatedPort,{path:'/v1/chat/completions',method:'POST',headers:{Authorization:`Bearer ${isolatedKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:'leaktest/m',messages:[{role:'user',content:'hi'}]})});assert.equal(r.status,401);assert.ok(!r.raw.includes(secret));assert.ok(!r.raw.includes('password'));assert.match(r.raw,/\[redacted\]/);}finally{isolatedChild.kill('SIGTERM');await sleep(100);await new Promise(resolve=>upstream.close(resolve));rmSync(isolated,{recursive:true,force:true});}});
 await test('legacy unrestricted admin proxy endpoint is disabled',async()=>{const r=await request(port,{path:'/admin/proxy/api/admin/v1/accounts',headers:auth});assert.equal(r.status,404);});
 await test('restore without keyStats preserves current stats section',async()=>{const backup=await request(port,{path:'/admin/backup',headers:auth});assert.equal(backup.status,200);delete backup.json.keyStats;const statsFile=join(data,'provider-key-stats.json');writeFileSync(statsFile,JSON.stringify({version:1,stats:{sentinel:{key:{requests:7}}}}));const before=readFileSync(statsFile,'utf8');const preview=await request(port,{path:'/admin/restore?preview=1',method:'POST',headers:jsonAuth,body:JSON.stringify(backup.json)});assert.equal(preview.status,200);assert.equal(readFileSync(statsFile,'utf8'),before);});
 await test('backup is redacted and unsupported plaintext export is rejected',async()=>{const r=await request(port,{path:'/admin/backup',headers:auth});assert.equal(r.status,200);assert.equal(r.json?.version,2);assert.equal(r.json?.secrets,'redacted');assert.ok(!r.raw.includes(KEY));const x=await request(port,{path:'/admin/backup?secrets=plain',headers:auth});assert.equal(x.status,400);assert.equal(x.json?.code,'secret_export_unsupported');});
 await test('invalid restore does not mutate provider state',async()=>{const before=readFileSync(join(data,'providers.json'),'utf8');const r=await request(port,{path:'/admin/restore',method:'POST',headers:jsonAuth,body:JSON.stringify({version:2,secrets:'redacted',providers:{providers:{bad:{name:'bad',baseUrl:'https://example.com/v1',models:[{id:'m'}],keys:[{id:'x',key:'plaintext'}]}}}})});assert.equal(r.status,400);assert.equal(readFileSync(join(data,'providers.json'),'utf8'),before);});
 await test('budget fields persist and disable action is enforced before dispatch',async()=>{const add=await request(port,{path:'/admin/providers',method:'POST',headers:jsonAuth,body:JSON.stringify({prefix:'budgeted',name:'budgeted',type:'openai',baseUrl:'https://example.com/v1',key:'secret',models:[{id:'m'}],budget:1,budgetAction:'disable'})});assert.equal(add.status,200);const p=JSON.parse(readFileSync(join(data,'providers.json'),'utf8'));assert.equal(p.providers.budgeted.budget,1);const id=p.providers.budgeted.keys[0].id;writeFileSync(join(data,'provider-key-stats.json'),JSON.stringify({version:1,stats:{budgeted:{[id]:{spentCredit:2,status:'active'}}}}));await request(port,{path:'/admin/providers/reload',method:'POST',headers:jsonAuth,body:'{}'});const r=await request(port,{path:'/v1/chat/completions',method:'POST',headers:jsonAuth,body:JSON.stringify({model:'budgeted/m',messages:[{role:'user',content:'hi'}]})});assert.equal(r.status,429);assert.equal(r.json?.error?.code,'provider_budget_exceeded');});
} finally {child.kill('SIGTERM');await sleep(100);rmSync(data,{recursive:true,force:true});}
console.log(`\n${pass} passed, ${fail} failed`);if(fail){console.error(stderr);process.exit(1);}
